package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFunction<M extends BaseFunction<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setFunctionname(java.lang.String functionname) {
		set("functionname", functionname);
		return (M)this;
	}

	public java.lang.String getFunctionname() {
		return get("functionname");
	}

	public M setFatherid(java.lang.Integer fatherid) {
		set("fatherid", fatherid);
		return (M)this;
	}

	public java.lang.Integer getFatherid() {
		return get("fatherid");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public M setOrdernum(java.lang.Integer ordernum) {
		set("ordernum", ordernum);
		return (M)this;
	}

	public java.lang.Integer getOrdernum() {
		return get("ordernum");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public M setRel(java.lang.String rel) {
		set("rel", rel);
		return (M)this;
	}

	public java.lang.String getRel() {
		return get("rel");
	}

}
