package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setIdcard(java.lang.String idcard) {
		set("idcard", idcard);
		return (M)this;
	}

	public java.lang.String getIdcard() {
		return get("idcard");
	}

	public M setBankcardno(java.lang.String bankcardno) {
		set("bankcardno", bankcardno);
		return (M)this;
	}

	public java.lang.String getBankcardno() {
		return get("bankcardno");
	}

	public M setUnitname(java.lang.String unitname) {
		set("unitname", unitname);
		return (M)this;
	}

	public java.lang.String getUnitname() {
		return get("unitname");
	}

	public M setSalaryid(java.lang.String salaryid) {
		set("salaryid", salaryid);
		return (M)this;
	}

	public java.lang.String getSalaryid() {
		return get("salaryid");
	}

	public M setRealname(java.lang.String realname) {
		set("realname", realname);
		return (M)this;
	}

	public java.lang.String getRealname() {
		return get("realname");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}

	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setSalt(java.lang.String salt) {
		set("salt", salt);
		return (M)this;
	}

	public java.lang.String getSalt() {
		return get("salt");
	}

	public M setCreatid(java.lang.Integer creatid) {
		set("creatid", creatid);
		return (M)this;
	}

	public java.lang.Integer getCreatid() {
		return get("creatid");
	}

	public M setCreatlevle(java.lang.Integer creatlevle) {
		set("creatlevle", creatlevle);
		return (M)this;
	}

	public java.lang.Integer getCreatlevle() {
		return get("creatlevle");
	}

	public M setIsfeedback(java.lang.Integer isfeedback) {
		set("isfeedback", isfeedback);
		return (M)this;
	}

	public java.lang.Integer getIsfeedback() {
		return get("isfeedback");
	}

}
