package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRolefunction<M extends BaseRolefunction<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setRoleid(java.lang.Integer roleid) {
		set("roleid", roleid);
		return (M)this;
	}

	public java.lang.Integer getRoleid() {
		return get("roleid");
	}

	public M setFunctionid(java.lang.Integer functionid) {
		set("functionid", functionid);
		return (M)this;
	}

	public java.lang.Integer getFunctionid() {
		return get("functionid");
	}

}
