package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("f_files", "id", FFiles.class);
		arp.addMapping("m_banner", "id", MBanner.class);
		arp.addMapping("s_user", "id", SUser.class);
		arp.addMapping("t_function", "id", Function.class);
		arp.addMapping("t_role", "id", Role.class);
		arp.addMapping("t_rolefunction", "id", Rolefunction.class);
		arp.addMapping("t_roleuser", "id", Roleuser.class);
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_userlog", "id", Userlog.class);
	}
}

