package com.demo.common.model;

import com.demo.common.model.base.BaseFFiles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FFiles extends BaseFFiles<FFiles> {
	public static final FFiles dao = new FFiles().dao();
}
