package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Function extends BaseFunction<Function> {
	public static final Function dao = new Function().dao();
	/**
	 * 查看admin的所有功能（即系统的所有功能）
	 * @return
	 */
	public List<Function> selectAllLv1Admin(){
		return find("select * from t_function where fatherid=0 order by ordernum asc");
	}
	/**
	 * 根据用户的id查看用户具有的一级功能
	 * @param userid
	 * @return
	 */
	public List<Function> selectLv1FunctionsByUserid(Integer userid){
		return find("select f.* from(select DISTINCT f.fatherid from t_roleuser ru "
				+ "inner join t_rolefunction rf on ru.roleid=rf.roleid inner join t_function f on rf.functionid=f.id "
				+"where ru.userid=?)t " 
				+"inner join t_function f on t.fatherid=f.id  order by f.ordernum asc",userid);
	}
	
	public List<Function> selectLv1Functionnone(Integer functionid){
		return find("select * from t_function where id=? order by ordernum asc",functionid);
	}
	/**
	 * 查询子菜单的功能列表
	 * @param fatherid
	 * @param userid
	 * @param username
	 * @return
	 */
	public List<Function> selectLv2FunctionsByFatheridUserid(Integer fatherid,Integer userid,String username){
		if(username!=null&&username.equalsIgnoreCase("admin"))
		{
			return find("select * from t_function where fatherid=? order by ordernum asc ",fatherid);
			
		}else{
			
		
				return find("select f.* from ("
						+ "select DISTINCT f.id from t_roleuser ru "
						+"inner join t_rolefunction rf on ru.roleid=rf.roleid "
						+"inner join t_function f on rf.functionid=f.id "
						+"where ru.userid=? and f.fatherid=?)t  "
						+"inner join t_function f on t.id=f.id "
						+"order by f.ordernum asc",userid,fatherid);
						
				
			}
		
	}
	
	public List<Function> selectLv1FunctionsByRoleid(Integer roleid){
		return find("select t.*,(select count(1) from t_rolefunction where fatherid=t.id and roleid=?)subcount 	from t_function t "
				+ "where t.fatherid=0 order by t.ordernum asc",roleid);
	}
	
	public List<Function> selectLv2FunctionsByFatheridRoleid(Integer fatherid,Integer roleid){
		return find("select t.*,IFNULL(rf.id,0)hasauth  "
				+ "from t_function t "
				+ "left join (select * from t_rolefunction where roleid=?)rf on t.id=rf.functionid where t.fatherid=?",roleid,fatherid);
	}
}
