package com.demo.common.model;

import com.demo.common.model.base.BaseMBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MBanner extends BaseMBanner<MBanner> {
	public static final MBanner dao = new MBanner().dao();
}
