package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseRoleuser;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roleuser extends BaseRoleuser<Roleuser> {
	public static final Roleuser dao = new Roleuser().dao();
	
	
	public Roleuser selectone(Integer userid) {
		
		String sql="select * from t_roleuser where userid=?";
		Roleuser roleuserm =Roleuser.dao.findFirst(sql, userid);
		return roleuserm;
	}
	
	public boolean delete(Integer roleid,Integer userid){
		return Db.update("delete from t_roleuser where roleid=? and userid=?",roleid,userid)>0;
	}
	
	/**
	 * 根据roleid删除表中数据
	 * @param roleid
	 * @return
	 */
	public Integer deleteByRoleid(Integer roleid){
		return Db.update("delete from t_roleuser where roleid=?", roleid);
	}
	/**
	 * 根据roleid查找表中数据
	 * @param roleid
	 * @return
	 */
	public List<Roleuser> selectByRoleid(Integer roleid){
		return find("select tru.*,tum.username from t_roleuser tru inner join t_user tum on tru.userid = tum.id where tru.roleid = ?", roleid);
	}
}
