package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role me = new Role().dao();
	
	public  List<Role> selectAll(){
		return me.find("select * from t_role order by rolename asc");
	}
	
	/**
	 * 根据角色名查找角色组
	 * @param name
	 * @return
	 */
	public List<Role> selectByName(String name){
		return find("select * from t_role where rolename=?",name);
	}
}
