package com.demo.common.model;

import com.demo.common.model.base.BaseSToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SToken extends BaseSToken<SToken> {
	public static final SToken dao = new SToken().dao();
}
