package com.demo.common.model;

import com.demo.common.model.base.BaseSUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SUser extends BaseSUser<SUser> {
	public static final SUser dao = new SUser().dao();
	
	public void set(){
	}
}
