package com.demo.common.model;

import java.util.Date;

import com.demo.common.model.base.BaseUserlog;
import com.jfinal.plugin.activerecord.Page;
import com.mysql.jdbc.StringUtils;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userlog extends BaseUserlog<Userlog> {
	public static final Userlog dao = new Userlog().dao();
	
	/**
	 * 
	 * @param userid 当前登录用户
	 * @param type 操作分类
	 * @param ip ip地址
	 * @param opcontent  操作内容
 	 * @return
	 */
   public Boolean addLog(Integer userid,Integer type,String ip,String opcontent){
		
		return new Userlog().set("userid", userid).set("loginip",ip).set("type", type).set("opcontent",opcontent).set("time",new Date()).save();
	} 
	/**
	 * 
	 * @param userid 当前登录用户
	 * @param type 操作分类
	 * @param ip  ip地址
	 * @return
	 */
   public Boolean addLog(Integer userid,Integer type,String ip){
		
		return addLog(userid,type,ip,null);
	}
	
   /**
    * 
    * @param userid 当前登录用户
    * @param type 操作分类
    * @return
    */
   public Boolean addLog(Integer userid,Integer type){
		
		return addLog(userid,type,null);
	} 
   
   /**
    * 根据用户编号和用户名查询操作日志
    * @param userid
    * @param pageNumber
    * @param pageSize
    * @param username
    * @return
    */
   public Page<Userlog> selectUserLogs(Integer userid,Integer pageNumber,Integer pageSize,String username,String keywords,String funName,String content,String startTime,String endTime){
	   String sql = "from t_userlog tlog inner join t_user tuser on tlog.userid = tuser.id "
	   		+ "inner join t_function tfun on tlog.type = tfun.id   where 1 = 1";
	   if(!StringUtils.isNullOrEmpty(keywords)){
		   sql+=" and (username like '%"+keywords+"%' or realname like '%"+keywords+"%')";
	   }
	   if(!StringUtils.isNullOrEmpty(funName)){
		   sql+=" and tfun.functionname like '%"+funName+"%'";
	   }
	   if(!StringUtils.isNullOrEmpty(content)){
		   sql+=" and tlog.opcontent like '%"+content+"%'";
	   }
	   if(!StringUtils.isNullOrEmpty(startTime)){
		   sql+=" and tlog.time>'"+startTime+"'";
	   }
	   if(!StringUtils.isNullOrEmpty(endTime)){
		   sql+=" and tlog.time<'"+endTime+"'";
	   }
	   if(!username.equals("admin")){
		   sql+=" and tlog.userid="+userid;
	   }
	   sql+=" order by tlog.time desc ";
	   return paginate(pageNumber, pageSize, "select tlog.loginip,tlog.opcontent,tlog.time,tuser.username,tuser.realname,tfun.functionname ", sql);
		 
	   
   }
}
